### ISSUE TITLE
Undefined names: dask and trial_contents

### ISSUE THREAD

**Issue by cclauss** [RJT1990/mantra#3]
[flake8](http://flake8.pycqa.org) testing of https://github.com/RJT1990/mantra on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
/home/travis/virtualenv/python3.7.0/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
./mantraml/templates/models/pytorch/base/model.py:14:21: F821 undefined name 'dask'
        self.data = dask
                    ^
./mantraml/templates/models/keras/base/model.py:14:21: F821 undefined name 'dask'
        self.data = dask
                    ^
./mantraml/templates/models/tensorflow/base/model.py:14:21: F821 undefined name 'dask'
        self.data = dask
                    ^
./mantraml/templates/models/default/base/model.py:15:21: F821 undefined name 'dask'
        self.data = dask
                    ^
./mantraml/tests/test_model_tensorflow.py:14:21: F821 undefined name 'dask'
        self.data = dask
                    ^
./mantraml/ui/core/views.py:358:48: F821 undefined name 'trial_contents'
            new_contents = [trial for trial in trial_contents if not trial[2] == trial_hash]
                                               ^
./mantraml/ui/core/views.py:361:57: F821 undefined name 'trial_contents'
                trial_folder_name = [trial for trial in trial_contents if trial[2] == trial_hash][0][1]
                                                        ^
7     F821 undefined name 'dask'
7
```

**Comment by RJT1990** [comment]
Thanks for the bug report - is a typo in one of the templates. Am pushing a fix now.

**Comment by RJT1990** [comment]
Just pushed a new release 0.962 that fixes this. Thank you!

**Comment by cclauss** [comment]
These tests still return the same results when run against the __master__ branch.  WIll this project leverage [GitHub releases](https://github.com/RJT1990/mantra/releases)?

**Comment by RJT1990** [comment]
Yes - will look to leverage GitHub releases going forward. We (+ @rstojnic) are just finalising a few things and then we can provide more information on the project (e.g. roadmaps) to help people contribute to the project. Thanks again

**Comment by cclauss** [comment]
‘dask’ issues are nowfixed but ‘trial_content’ issues are not.

**Comment by RJT1990** [comment]
Thanks - was a missing variable in one of the UI forms for deleting trials. This should now be resolved in the latest push. 

It also seems there's an F822 undefined name 'test' in __all__ which is coming from the numpy library.
